### ISSUE TITLE
Pokemon Red - Green Menu

### ISSUE THREAD

**Issue by rossimo** [rossimo/retrobot#2]
The Pokemon list menu occasionally turns green.

![Screenshot_20220913_125258](https://user-images.githubusercontent.com/719699/190150176-899e4a5c-d5d3-4874-a204-6307ddec35c0.jpg)

**Comment by rossimo** [comment]
test

**Comment by rsquires** [comment]
Loading the attached savestate and pressing "a" will replicate the issue.

[Pokemon Red.zip](https://github.com/rossimo/retrobot/files/9607502/Pokemon.Red.zip)

**Comment by rossimo** [comment]
Attached are example frames. They've gone through the bot's RGB565 -> RAW ->BMP conversion, then additionally converted to PNG to be compatible with Github.

I wonder if one of the other image formats in mGBA (other than RGB565) would provide a better result?

![frame-0](https://user-images.githubusercontent.com/719699/191259869-e61a5afd-06ce-47b1-94b3-6262e03a5f74.png)
![frame-3](https://user-images.githubusercontent.com/719699/191259871-071db18a-2c71-4789-9f7c-26c77c60fa34.png)
![frame-39](https://user-images.githubusercontent.com/719699/191259872-9003b329-ed54-4c36-956e-5e0d2125839c.png)
![frame-42](https://user-images.githubusercontent.com/719699/191259873-f6690128-64df-4f25-b21b-4dcdc8e38d62.png)
![frame-48](https://user-images.githubusercontent.com/719699/191259875-ed54870f-1c5f-4504-824a-11ade300d056.png)
![frame-53](https://user-images.githubusercontent.com/719699/191259876-e0a52042-78e0-494e-ab5d-c96c49a1a4d1.png)
![frame-58](https://user-images.githubusercontent.com/719699/191259877-d28e474c-086e-42d7-b060-1867a16e42e2.png)
![frame-63](https://user-images.githubusercontent.com/719699/191259878-d9ddb61c-9a5f-4bc2-a6d7-7c52266d1a54.png)
![frame-68](https://user-images.githubusercontent.com/719699/191259880-80163d9b-685a-42d8-be25-6a97ce4d1e34.png)
![frame-73](https://user-images.githubusercontent.com/719699/191259883-f8380031-a185-4f48-9bee-6352fd3d46e5.png)
![frame-78](https://user-images.githubusercontent.com/719699/191259885-54411284-de36-4936-89cc-f7d03cc0d220.png)
![frame-83](https://user-images.githubusercontent.com/719699/191259886-af2a5cd1-ddbc-4a6c-853d-5b21cc38f9c6.png)
![frame-88](https://user-images.githubusercontent.com/719699/191259890-a29846a4-1fde-4224-8495-ef768a12f156.png)
![frame-93](https://user-images.githubusercontent.com/719699/191259891-71d07bc2-402e-43b7-8f73-2c82bd1f5bac.png)
![frame-98](https://user-images.githubusercontent.com/719699/191259893-cab8807b-80c9-4bad-99b8-c083982f689d.png)

**Comment by rsquires** [comment]
This has been fixed with https://github.com/rossimo/retrobot/commit/b6881c39f471da96e2dbdbad4c53b1f911cd91d1.

**Comment by rossimo** [comment]
This has been fixed with https://github.com/rossimo/retrobot/commit/b6881c39f471da96e2dbdbad4c53b1f911cd91d1

**Comment by oblivioncth** [comment]
I still experience this with the latest docker image.

![image](https://user-images.githubusercontent.com/24661585/216490621-1758a483-5007-4cb4-9a4d-f43942f6705c.png)

**Comment by Casuallynoted** [comment]
Same here^
